name: cicd pipeline


on: 
  workflow_dispatch:
    inputs:
      environment:
        description: This is enviornment values where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
            prod
            staging

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Developer code task
        run: echo "Developer code"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build the code 
        run: echo "COde build"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code
        run: echo "COde deploy"

  
