name: cicd pipeline


on: 
  workflow_dispatch:
    inputs:
      environment:
        description: This is enviornment values where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Developer code task
        run: echo "Developer code"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build the code 
        run: echo "COde build"

  deploy:
  # It will deploy only when u enter 'dev' in inputs option. If you give prod it won't deploy it.
    if: inputs.environment == 'dev'
  # It will only run when code & build job executes successfully
    needs:
      - code
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code
        run: echo "COde deploy"

  
